### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by lazyDefender** [lazyDefender/homepage1#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by roman-ortynskyi** [comment]
I'm a student of Software Engineering. I'm committed to developing my skills in information technology. Capable of delivering effective solutions to customer's problems. Hardworking and ready to join my next team.

You gotta have a dream. If you don't have a dream, how you gonna have a dream come true?
