### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by lazyDefender** [lazyDefender/homepage1#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by roman-ortynskyi** [comment]
- Linkedin [linkedin.com/in/roman-ortynskyi-2719b8204](https://www.linkedin.com/in/roman-ortynskyi-2719b8204/)
- Email [ortynsky1@gmail.com](mailto:ortynsky1@gmail.com)
- Instagram [instagram.com/rroman_ortynsky](https://www.instagram.com/rroman_ortynsky/)
